[project]
name = "pid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.0.0",
    "scipy>=1.14.0",
    "plotly>=5.24.0",
    "dash>=2.18.0",
    "dash-bootstrap-components>=1.6.0",
]
